databases:
  - name: transport_db
    databaseName: transport_db
    user: transport_user

services:
  - type: web
    name: transport-project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn transport_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: transport_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
